### PR TITLE
Ру fixes: chaH

### PR DESCRIPTION
**Pull request by RedJimi**
Unifying and fixing pronouns to a dictionary standard.

### CODE REVIEW

**Comment by mycatisavulcan** [comment]
Yes looks good

**Comment by mycatisavulcan** [comment]
Change "для говорящих существ" to "для носителей языков"

**Comment by De7vID** [comment]
What's the difference between "для говорящих существ" and "для носителей языков"?

**Comment by mycatisavulcan** [comment]
"для носителей языков" is the correct way in Russian to refer to language users . "для говорящих существ" means "for talking creatures/things", and it gives off a completely wrong impression while only being correct on a technicality

**Comment by RedJimi** [comment]
The chaH definition is now fixed according to mycatisavulcans instructions

**Comment by RedJimi** [comment]
ghaH also updated.

**Pull request merged**
