### PR TITLE
modify xml2json.py script to be aware of locales other than 'de'

### PR DESCRIPTION
**Pull request by dlyongemallo**

### CODE REVIEW

**Comment by De7vID** [comment]
@dadap - Is this change necessary and/or sufficient?

**Comment by dadap** [comment]
This is the solution I came up with, but I’m running into some trouble with the search tag fields. I haven’t yet determined whether the problem is in the JSON generation or the parsing, but I’ll get a better look at it soon. Stay tuned: https://github.com/dadap/klingon-assistant-data/commit/0f3f238bdc58a86f08ae462b842aff6f83efec26

**Comment by dadap** [comment]
I identified and fixed the issue I ran into which is described in the above comment. The problem was in my updates to xml2json.py; the new database is backwards compatible with the existing Flutter version of boQwI'. Once #58 is merged, this PR won't be needed.

**Comment by dadap** [comment]
Closing

**Pull request closed without merging**
