### PR TITLE
Split {meq:n} and {quv:v} to two homonyms each

### PR DESCRIPTION
**Pull request by fergusq**

### CODE REVIEW

**Comment by De7vID** [comment]
I'll have to think about this one. I don't know if these would be considered separate words "in Klingon", and I've been accused of editorialising in the past when I've made changes like this.

**Comment by LievenLitaer** [comment]
I would not split **meq** or **quv** into two homonyms, because – as you say – I do not consider them as true homonyms, at least from a Klingon point of view. "homonym" means the me if one word has two absolute different meanings, like **jIH** or **jav**.

**Comment by fergusq** [comment]
They are different senses more than homonyms, but unfortunately this dictionary does not have support for different senses, so we are forced to either separate them as different homonyms or not separate them at all.

boQwI' already has this kind of entries. **pup:v:2**, **'al:v:2**, **Dop:v:2**, for example. It would be consistent with them to split **quv** and **meq** too. If we decide only to include true homonyms, we should consider removing the existing splitted entries, but I don't think that would improve the dictionary from the reader's point of view.

**Comment by De7vID** [comment]
> boQwI' already has this kind of entries. **pup** (v:2), **'al** (v:2), **Dop** (v:2), for example. 

I don't think those examples are similar to the ones under consideration (though maybe examples do exist that I haven't found). **boQwI'** does split entries where a general sense of the verb is one entry, and a specific application of that sense to a domain is a separate entry. For example, this is true of mathematics terminology, like **boq** (*v*). So **'al** (*v*) and **Dop** (*v*) are following this pattern. **pup** (*v*) has a general meaning of "be perfect, exact", and a more specific meaning of "be high-resolution" when applied to devices, so the second entry is also domain-specific. 

**quv** is applied to people and means "be honored". It just happens that we translate **vutwI' quv** as "head chef" and **yejquv** as "High Council", but the Klingon terms are indeed just "honored cook" and "honored council". The meaning is not different, nor is the domain. It's just that a particular way of translating those terms sound more natural in English. 

I think the same thing is true for **meq**. All of its meanings apply to the domain of something like analytic discourse. It's just that the Klingon word is broader than any of its English definitions. (Speculatively, maybe the way you narrow the meaning is with a construction like **ngoQ meq** for "motive" and **rIchmeH meq** for "subject", but **meq** by itself seems to cover both of those in its meaning.)

I don't know if the database is entirely consistent in splitting off domain-specific specialised meanings like this, but at least that's the intention, and **quv** and **meq** don't seem to me to fit that case.

**Comment by fergusq** [comment]
I think, from an English-speaking reader's perspective, the two meanings of **quv** are different and valuable to know.

The presence of **vutwI' quv** and **ghojmoHwI' quv** tell us that this sense of **quv** is not limited to specific words like **yejquv**. The two meanings are also orthogonal: I see no problem with saying eg. **quvHa' yejquv** *the high council is dishonorable* or **quvHa' vutwI' quv** *the head chef is dishonorable*.

It is possible that Klingons do not perceive these as different senses, but I think including them would be practical from the perspective of the dictionary user. Currently, if the user searches for **quv**, they will only find the "(literally) honorable" sense, but the text could as well refer to a person who is in a high position without being actually honorable, and in this case the dictionary is confusing.

I think that it would be nice to add this as a separate entry, as it has a lot of examples that are clearly distinct from the examples of the literal meaning. But if you think it is not worth of a different entry from the lexicographic point of view, it can also be added to the notes of the main entry.

**Pull request closed without merging**
