### PR TITLE
Updated many Swedish translations, added ZDB tools

### PR DESCRIPTION
**Pull request by zrajm**
Worked through and fixed many Swedish translations, removing the relevant '[AUTOTRANSLATED]'.

I also created a couple of small tools to simplify my editing in Emacs. These are called `xml2zdb.pl` and `zdb2xml.pl` respectively, it'd be nice if you could include them in the repository as well. (They are quite simplistic, but there are comments at the beginning of each script explaining how to use them.)

My commit also affect the indentation of some parts of the XML (indentation was varying slightly in different parts of the XML files, probably as a result of them being handwritten, while my `zdb2xml.pl` is completely regular in its output.) – This means that you'll get some noise in the diffs unless you use the `-b` option of `git diff`.

### CODE REVIEW

**Comment by De7vID** [comment]
Is there no way to preserve the indentation? They're actually meaningful: indentation indicates subentries, and is used to group entries together under the same heading which are displayed together in the app. (From a code point of view, the only meaningful thing is the order, but the indentation explains to a reader why the entries are not in strict "alphabetical" order.) Also, the newlines between sections should be preserved.

While this format makes it easier for a machine to digest, it loses a lot of human-readability.

**Comment by fergusq** [comment]
I have also had problems with the indentation. I have a script that finds all untranslated words and prompts me to translate them to Finnish. It sometimes misindents the lines and then I have had to manually fix them. (Of course I should just make the script preserve indentation, but I haven't yet bothered to do it.)

Could this information be encoded using proper XML notation? For example, could you make a `<subentries>` tag that would contain the entries that are now indented? Then it would be easier to just run standard XML formatting after editing the files to ensure that they are properly indented.

**Comment by De7vID** [comment]
It _could_ be done in the XML, but the indentation is mostly for human editors (I guess primarily me) who can tell at a glance, when adding a new entry, that it should go, e.g., below the subentries of the previous entry, even though it should be sorted earlier by "alphabetical" order.

Of course, instead of relying on humans to do this, there should probably be a well-defined set of rules which sorts subentries automatically. But this is somewhat difficult as the existing sort order involved a lot of judgment, e.g., names below common words, words made up by other authors but "blessed" by Okrand after words actually invented by him, etc. Basically the ordering in the XML affects how the results show in up **boQwI'**, so there's been a lot of manual decisions made to put entries which are likelier to be "useful" to more users earlier in the results.

I guess this _could_ be encoded in a field that modifies the sort order but at this point I'm not very keen on changing the database format (due to its fragility).

**Comment by zrajm** [comment]
> Is there no way to preserve the indentation?

The tools Do preserve indentation! Just not the fact that some entries are indented more than others.

**Comment by De7vID** [comment]
> > Is there no way to preserve the indentation?
> 
> The tools Do preserve indentation! Just not the fact that some entries are indented more than others.

I'm confused about this statement. The fact that some entries are indented more than others _is_ the indentation that needs to be preserved.

For example, the subentries of **baS**, such as **baS Ha'on**, which should all appear before **baSta'**, should be indented more than their parent entry **baS**. This indentation is removed in the PR.

**Comment by De7vID** [comment]
Oh, wait, I just realised that this PR does more than change the indentation, it destroys the manually curated sorting information. For example, if the user types **bIQ**, the app is supposed to show **bIQ** followed by **bIQ bal** and other entries beginning with **bIQ**, and sentences which happen to begin with **bIQ**, such as **bIQapqu'meH tar DaSop 'e' DatIvnIS** should appear after all the **bIQ** subentries. With this PR, these sentences are sorted before the subentries of **bIQ**.

**Comment by zrajm** [comment]
> > > Is there no way to preserve the indentation?
> > 
> > 
> > The tools Do preserve indentation! Just not the fact that some entries are indented more than others.
> 
> I'm confused about this statement. The fact that some entries are indented more than others _is_ the indentation that needs to be preserved.
> 
> For example, the subentries of **baS**, such as **baS Ha'on**, which should all appear before **baSta'**, should be indented more than their parent entry **baS**. This indentation is removed in the PR.

Ah, so the fact that some entries are indented more than others is carries *meaning*? That's not something I expected. I'll have to look at the data again with that in mind! (Spacing doesn't normally have any significance in XML, so i wasn't looking for that and it totally went over my head.)

Let me see if i can resubmit this during the day, in some more sensible way.

Also, how is this sorting information you speak of stored in the data? It seems Wierd that in commit should've affected That!

**Comment by De7vID** [comment]
> Ah, so the fact that some entries are indented more than others is carries _meaning_? 

Not as such. It's actually the sort order that carries meaning, but the indentation reflects that. The file looks like this (showing just two subentries under **bIQ** for simplicity):

+ **bIQ**
    * **bIQ bal**
    * **bIQ Duj**
+ **bIQapqu'meH...**

The consequence of ordering the entries this way is that if the user types "bIQ", the results show up in the order specified above. It's only when the user types "bIQa" that the sentence becomes the first result.

The file could as well have been written like this, with no indentation:

+ **bIQ**
+ **bIQ bal**
+ **bIQ Duj**
+ **bIQapqu'meH...**

The indentation carries no meaning per se. As far as the scripts are concerned, the indentation isn't there. It's the sort order that carries the meaning. The indentation is really only there to help a person see _why_ **bIQ bal** should be sorted before **bIQapqu'meH...**.

Your PR changes the sort order into this:

+ **bIQ**
+ **bIQapqu'meH...**
+ **bIQ bal**
+ **bIQ Duj**

This is not a noop. It has the effect that a user typing "bIQ" will see the sentence **bIQapqu'meH...** _before_ the **bIQ** subentries, which is undesirable.

Maybe it's possible to automate the sorting in a way that approximately reproduces the current sort order. The decisions I've made when sorting entries has been somewhat ad hoc and possibly inconsistent, so actually putting down actual rules in code might improve things. But that's out of scope for this PR.

**Comment by De7vID** [comment]
This is too out-of-date to merge.

**Pull request closed without merging**
