### PR TITLE
Rework www.youtube.com/v/ links to www.youtube.com/watch?v=

### PR DESCRIPTION
**Pull request by dadap**
For some reason, /v/<video_id> doesn't work on Mobile Safari when
following a link to a YouTube video in a WebView from the Flutter port,
but /watch?v= does work.

### CODE REVIEW

**Comment by dadap** [comment]
Hi De'vID, not sure how this affects older Android versions - if you think this will be problematic I can work around this on the app side, but it would be nice to not have to treat YouTube links specially.

**Comment by De7vID** [comment]
Another case where I wish I'd made a design decision earlier to have a special tag for YouTube videos (like "{[description]:youtube:[id]}" instead of "{...:url:...}". Again, I'm stuck with using the generic "url" tag because of the older versions, whose codebases I don't want to touch.

That said, it seems that we can replace "www.youtube.com/v/" with "youtu.be/" on Android. Does that work on iOS?

**Comment by De7vID** [comment]
Also: did you test with the YouTube app both installed and uninstalled?

**Comment by dadap** [comment]
I only tested with YouTube installed. On iOS it opens in a Mobile Safari webview, so it would probably do that without the app too, and on Android (I tested 5.1 and 7.1) it opens in the YouTube app, and presumably does something sensible without the app installed.

I can test http://youtu.be/ - I expect it should work. If it works on the cross product of {Android, iOS} x {YouTube installed, YouTube not installed}, I’ll discard this pull request and open a new one. If it doesn’t work, I’ll retest this change without YouTube installed and update this PR.

**Comment by De7vID** [comment]
It seems that the "/v/" link was actually an old (like *really* old) way to display the video full-screen, using Adobe Flash! (If you try to use it now, on a browser which doesn't have Adobe Flash installed, it in fact will generate and download a .swf file!) The YouTube (Android) app actually overrides this link to open up in the app instead.

The recommended way to link to YouTube is actually with the "youtu.be"-style link, so this should work on iOS. I'd be surprised if it doesn't. If the app isn't installed, then YouTube is open on a browser.

Fortunately (or unfortunately, for the users), we don't have to worry about older Android versions as YouTube is deprecated for those versions. I tried linking to YouTube on both legacy versions of the app, and get an error message that YouTube is no longer supported on those devices.

**Comment by De7vID** [comment]
I've updated the link to the "youtu.be" style and pushed a new beta.

**Comment by dadap** [comment]
Yep, working on iOS now with your recent change. This PR can be closed.

**Comment by dadap** [comment]
Also, interesting find with the Flash thing - that certainly explains why the /v/ links didn’t work on iOS!

**Pull request closed without merging**
