### PR TITLE
Translated extra and examples to Finnish + improved some translations

### PR DESCRIPTION
**Pull request by fergusq**
Regarding the translation of the entry on "boQwI'" (the front page of the dictionary).

When translating "Klingon, Star Trek, and related marks are trademarks of CBS Studios, Inc., and are used under "fair use" guidelines." I left out the mention of "fair use" as that is a concept alien to the Finnish (and European) trademark law. There is no translation to it and it wouldn't mean anything legally, as I have understood it. I'm however no lawyer. What do you suggest?

### CODE REVIEW

**Comment by De7vID** [comment]
Given that the app is published on a platform owned by an American company, translate it as best as you can? Surely, someone somewhere has had to translate American legalese into Finnish.

Does the [Wikipedia page](https://fi.wikipedia.org/wiki/Fair_use) help at all?

**Comment by LievenLitaer** [comment]
As a translator of the German parts, I suggest simply mentioning the thing as what it is, maybe add the note that it's an American law. Identical as if you would write _"...and are used under "Mok'bara" guidelines."_ or _"...and are used under US law of "Mok'bara"."_

**Comment by fergusq** [comment]
I translated it the way Lieven Litaer suggested

**Comment by De7vID** [comment]
Thanks!

**Pull request merged**
