### PR TITLE
Feature/mem 01 b localization

### PR DESCRIPTION
**Pull request by barricade86**
Translated words in mem-01-b

### CODE REVIEW

**Comment by dadap** [comment]
Probably because of merge conflicts. They were trivial, so I resolved them and merged with #80.

**Comment by barricade86** [comment]
No. Because i missed with destination branch. I planned to make pull
request into the master branch, which in my forked repo. I have small
doubts about few words and sentences. When i resolve them, i merge my
branch with master(which in my forked repo).

вс, 8 июл. 2018 г., 19:59 Daniel Dadap <notifications@github.com>:

**Comment by dadap** [comment]
Oops. If that was your intention, I apologize, as it’s already merged. pelaQDaj ghorpu'. I did see a few translations that I wanted to ask questions about, but I figured we’d do a proofreading pass at some point.

My personal preference would be to merge early and merge often over having a bunch of unnerved branches that have conflicts that need resolving.

**Comment by De7vID** [comment]
It's not just merge conflicts. There are quite a few things which were in the wrong field. Also, not all `search_tags` need to be translated (and conversely, if there's a word a Russian user might search for to find an entry which isn't in the definition, you can add a `search_tags_ru` even if `search_tags` is empty). In particular, the canon definitions are (mostly) in American English, and the `search_tags` are used for for alternate (Canadian/British spellings) spellings. In that case, there's no need to translate the search tags to duplicate what's in the definition already.

**Comment by De7vID** [comment]
Also, the `examples` field doesn't need to be translated if it's only linking to other entries, or is otherwise only in Klingon. It only needs to be translated if it contains any English.

**Comment by barricade86** [comment]
Does it means, i shouldn't fill search_tags_ru at all for now?For now, i
filled it, if the search_tags filled.

вс, 8 июл. 2018 г., 21:47 De7vID <notifications@github.com>:

**Comment by De7vID** [comment]
That's up to you. The search tags are not intended or expected to be the same across languages.

Also, if there are multiple sentences in `examples`, and not all of them need to be translated, you have to leave (copy) the others ones, as otherwise they'll disappear in Russian. For example, there are 3 sentences under **bogh** but two point to other entries, so only one needs to be translated. The first two sentences have to be duplicated in the `examples_ru` field.

**Comment by dadap** [comment]
Sorry for jumping the gun on the resolve/merge/pull. I was so excited at the prospect of having a whole letter translated that I neglected to read the changes with a critical eye.

**Pull request closed without merging**
