### PR TITLE
Some de submissions for the new vocabulary.

### PR DESCRIPTION
**Pull request by dlyongemallo**

### CODE REVIEW

**Review by De7vID — COMMENTED** [review]
It looks slightly weird for the situation not to be symmetric with **ngolpel**, which currently has the German definition "Sit-up, Rumpfbeugen". Should the "Sit-up" be moved to `search_tags_de` too, or do German speakers really say "Sit-up" but not "Push-up"?

**Review by De7vID — COMMENTED** [review]
I don't see who makes the submissions. They're anonymous (and have to be, to respect the privacy policy).

**Comment by LievenLitaer** [comment]
It might seem weird to be not parallel, bit it's true. In daily speech, push-up is accepted, what the google results show. (and even here: see the image results!)
But indeed, "Sit-up" is a lot more common than "Push-up". Actually, I wouldn't even know what the German word for "sit-up" is.
I checked two trustworthy sources for this: 
1. Wikipedia uses "Sit-up" for the one and "Liegestütz" for the other.
2. Duden explains "sit-up" as the sports activity and "push-up" only for the bra.

**Comment by De7vID** [comment]
Okay, then it sounds like the **ngolpel** entry should be edited to move "Rumpfbeugen" to the `search_tag_de`.

**Comment by LievenLitaer** [comment]
I wouldn't say so; The wikipedia article starts with 
"**Sit-up** (auch: **Rumpfbeugen**, **Rumpfheben** oder **Aufrichter**) ist eine Trainingsübung,..."

**Comment by De7vID** [comment]
If you're okay with the way things are, you can merge the changes, preferably using "Squash and merge".

**Pull request merged**
