### PR TITLE
Script and template for generating a pdf

### PR DESCRIPTION
**Pull request by fergusq**
Use these commands to compile a pdf:

```sh
# dependency
pip install yajwiz

# generation
python xml2json.py >data.json
cd book
python generate-latex.py >content-en.tex
pdflatex book-en.tex
```

### CODE REVIEW

**Comment by fergusq** [comment]
I moved the relevant files from klingonia-utils here so that it won't call the server anymore. Instead, it will load the data.json file from the parent directory.

It required yajwiz, which can be installed with pip:

```sh
pip install yajwiz
```

It also expects that there is a data.json file, which should be generate before running this:

```sh
python xml2json.py >data.json
```

**Comment by fergusq** [comment]
It includes some unnecessary code that was used for HTML rendering which can be removed safely if wanted.

**Comment by De7vID** [comment]
Thanks!

The convention so far has been to put `#!/usr/bin/env python3` in the first line of python files and make them executable.

**Comment by De7vID** [comment]
Can you change the header font in the dictionary portion to a serif typeface, maybe the same one as in the text? Otherwise, there's the **I** vs. **l** confusion. 

I'm also wondering if the **qaghwI'** can be made to look more like what's in TKD (looks like a dot with tail, rather than a plain tick mark), but that's not so important.

**Comment by fergusq** [comment]
I can make the changes to the headers. I think I'll switch to XeTeX so we can use whatever font we want. Palatino is in my opinion best of the built-in fonts, but it might not be ideal for Klingon.

**Comment by De7vID** [comment]
Sure.

**Pull request merged**
